version: "3.8"

services:
  backend:
    build: ./backend
    container_name: skoolcampus-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - skoolcampus-net

  frontend:
    build: ./frontend
    container_name: skoolcampus-frontend
    restart: always 
    depends_on:
      - backend
    ports:
      - "8080:80"

    networks:
      - skoolcampus-net

networks:
  skoolcampus-net:
    external: true
