version: "3.8"

services:
  backend:
    build: ./backend
    container_name: skoolcampus-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - skoolcampus-net

  frontend:
    build: ./frontend
    container_name: skoolcampus-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # These are the certs created by certbot on the *host*
      - /etc/letsencrypt/live/skoolcampus.in/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/skoolcampus.in/privkey.pem:/etc/ssl/private/privkey.pem:ro
    networks:
      - skoolcampus-net

networks:
  skoolcampus-net:
    external: true
